### ISSUE TITLE
Error when download files which are not available anymore

### ISSUE THREAD

**Issue by combatlord** [AT0myks/reolink-fw-archive#24]
When I run "Download" I get the following error messages. 
It seems that the 4 files that are now unavailable are causing this error.

I use the latest Release 2023.07.13

Regards chris

```
Downloading 448 firmwares
Error 404: https://drive.google.com/uc?id=1MG2mYvj6nC6VkESnYLaOV3xSseEwnh-b&confirm=t
Error 403: https://drive.google.com/uc?id=1BDEwz2NVhJaQLvZJ11aElQzm-APxNP8a&confirm=t
Error 403: https://drive.google.com/uc?id=1RCume3f77oYMbZ3oD06cyD9O6F--uFiC&confirm=t
Error 403: https://drive.google.com/uc?id=16Q-iOSTpnkYaJoxzvFeY6YQbrOGbty12&confirm=t
444 successful
4 failures
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021C3D8BFD90>
Traceback (most recent call last):
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021C3D8BFD90>
Traceback (most recent call last):
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021C3D8BFD90>
Traceback (most recent call last):
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021C3D8BFD90>
Traceback (most recent call last):
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "E:\PortablePython3_x64\App\Python\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by AT0myks** [comment]
Only the 404 link is dead, for the 403 errors you just need to wait and try again later, as mentioned in the [wiki page](https://github.com/AT0myks/reolink-fw-archive/wiki). This page also mentions that the `RuntimeError: Event loop is closed` errors are normal on Windows and can be ignored.

I've replaced the dead link so it shouldn't give a 404 anymore, and I edited your comment to add a code block for the script's output.

**Comment by combatlord** [comment]
Yes your are rigth.
Sri, I really overlooked the wiki here. ;-)

**Comment by AT0myks** [comment]
Did you manage to download all firmwares without any error?

**Comment by combatlord** [comment]
Yes, now everything works. 448 Files and 0 failures
