### ISSUE TITLE
download.py failure

### ISSUE THREAD

**Issue by kfonda** [AT0myks/reolink-fw-archive#34]
I can't get the download.py script to run anymore.
All of the directories are created but nothing downloads

Using python 3.12.0 on Windows 10 or python 3.9.16 on linux I get the following error...

> Downloading 477 firmwares
Traceback (most recent call last):
  File "D:\Reolink\download.py", line 226, in <module>
    asyncio.run(main())
  File "C:\Users\kfond\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\kfond\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kfond\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Reolink\download.py", line 212, in main
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Reolink\download.py", line 140, in download
    filename = "__".join((model, hw_ver, version))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by AT0myks** [comment]
Reolink made some unexpected changes that resulted in some RLC-410 and RLC-410W firmwares being orphaned causing the issue you got. This was fixed in aa362a31d6ac819d367f3342319240cceeb46574. You don't have anything to do, simply rerun the command and that should work.
